# Generated by Django 4.1.5 on 2023-03-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
