# Generated by Django 4.1.5 on 2023-03-21 09:52

from django.db import migrations
import uuid

def add_uid(apps, schema_editor):
    User = apps.get_model('account', 'User')
    for obj in User.objects.all():
        print(obj)
        obj.uid = uuid.uuid4()
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_slug_user_uid'),
    ]

    operations = [
        migrations.RunPython(add_uid)
    ]
