# Generated by Django 4.1.5 on 2023-03-21 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d97b5bcf-38ec-4b17-8aeb-ee8688125eb5'), editable=False),
        ),
    ]
