# Generated by Django 4.1.5 on 2023-03-21 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('88b448e8-29e7-4356-a6b0-ece5f39c6830'), editable=False),
        ),
    ]
