# Generated by Django 4.1.5 on 2023-01-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_nick',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password2',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
