# Generated by Django 4.1.5 on 2023-01-28 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0002_user_user_nick_user_user_password2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='User_nick',
            new_name='user_nick',
        ),
    ]
