# Generated by Django 4.1.5 on 2023-01-30 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_ap', models.DateTimeField(auto_now_add=True)),
                ('penname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webtoon_author', to=settings.AUTH_USER_MODEL)),
                ('webtoon_like', models.ManyToManyField(related_name='webtoon_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_ap', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('webtoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_webtoon', to='webtoon.webtoon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
