# Generated by Django 4.1.5 on 2023-01-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fantasy', models.CharField(max_length=20)),
                ('Modern', models.CharField(max_length=20)),
                ('genre1', models.CharField(max_length=20)),
                ('genre2', models.CharField(max_length=20)),
                ('genre3', models.CharField(max_length=20)),
                ('genre4', models.CharField(max_length=20)),
                ('genre5', models.CharField(max_length=20)),
                ('genre6', models.CharField(max_length=20)),
                ('genre7', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=20)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
