# Generated by Django 4.1.5 on 2023-01-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nick', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=20)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
