# Generated by Django 4.1.5 on 2023-02-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
