# Generated by Django 4.1.5 on 2023-02-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0002_webtoon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='genre',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='tag',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
