# Generated by Django 4.1.5 on 2023-02-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0003_webtoon_genre_webtoon_tag_alter_webtoon_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_ap', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='genre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='image',
            field=models.ImageField(blank=True, upload_to='webtoon'),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='tag',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
