# Generated by Django 4.1.5 on 2023-02-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0004_category_alter_webtoon_genre_alter_webtoon_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='webtoonthumnail'),
        ),
    ]
