# Generated by Django 4.1.5 on 2023-03-21 21:33

from django.db import migrations, models
import webtoon.models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0006_alter_webtoon_image_alter_webtoon_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='image',
            field=models.ImageField(blank=True, upload_to=webtoon.models.upload_to_uid),
        ),
    ]
