# Generated by Django 4.1.5 on 2023-03-23 01:31

from django.db import migrations, models
import django.db.models.deletion
import webtoon.models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0007_alter_webtoon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='webtoon',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='webtoon.webtoon'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=webtoon.models.upload_to_uid),
        ),
    ]
